import type { Project } from "./types"

export const projects: Project[] = [
  {
    id: "zedos",
    slug: "zedos",
    name: "ZedOS",
    description: "Developer OS pessoal para centralizar workflow, memoria tecnica e automacoes.",
    status: "active",
    priority: "high",
    area: "Productivity",
    stack: ["React", "TypeScript", "Tailwind", "PostgreSQL"],
    updatedAt: "Hoje",
    nextAction: "Modelar Project, Note e Snippet no Prisma.",
    notesCount: 4,
    snippetsCount: 6,
  },
  {
    id: "api-lab",
    slug: "api-lab",
    name: "API Lab",
    description: "Ambiente de experimentos para padroes Node, Express, Prisma e PostgreSQL.",
    status: "backlog",
    priority: "medium",
    area: "Backend",
    stack: ["Node.js", "Express", "Prisma"],
    updatedAt: "Ontem",
    nextAction: "Definir estrutura de services e repositories.",
    notesCount: 2,
    snippetsCount: 5,
  },
  {
    id: "ui-system",
    slug: "ui-system",
    name: "UI System",
    description: "Biblioteca visual local baseada em shadcn/ui para telas densas e produtivas.",
    status: "active",
    priority: "medium",
    area: "Frontend",
    stack: ["shadcn/ui", "Radix", "Lucide"],
    updatedAt: "2 dias atras",
    nextAction: "Criar padroes de cards, listas e paineis.",
    notesCount: 3,
    snippetsCount: 7,
  },
  {
    id: "desktop-automation",
    slug: "desktop-automation",
    name: "Desktop Automation",
    description: "Ideias para automacoes locais e integracao futura com Tauri.",
    status: "paused",
    priority: "low",
    area: "Automation",
    stack: ["Tauri", "Node.js"],
    updatedAt: "Semana passada",
    nextAction: "Mapear comandos frequentes do workflow diario.",
    notesCount: 1,
    snippetsCount: 0,
  },
]
